name: stn-pytorch
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6.5
  - pip
  - numpy==1.17.2
  - pytest==5.1.1
  - pytorch==1.3.1
  - torchvision==0.4.2
  - cython=0.29.14
  - pillow=6.2.
  - matplotlib
